print('Введите вид питомца')
type = input()
print('Введите кличку питомца')
nickname = input()
print('Введите возраст питомца')
age = input()
print('Это ' + type + ' по кличке ' + nickname + '. Возраст: ' + age + ' года.')