print('Введите первый этап развития человека: ')
one = input()
print('Введите второй этап развития человека: ')
two = input()
print('Введите третий этап развития человека: ')
three = input()
print('Введите четвертый этап развития человека: ')
four = input()
print('Введите пятый этап развития человека: ')
five = input()

print(one, two, three, four, five, sep='=>')
